import { IntermediateRepresentation, Entity, EntityField } from '../types/floe';

function mapSqlType(field: EntityField): string {
  if (typeof field.type === 'string' && field.type.startsWith('ref:')) {
    return 'UUID';
  }

  switch (field.type) {
    case 'string':
      return 'VARCHAR(255)';
    case 'text':
      return 'TEXT';
    case 'number':
      return field.name.includes('days') || field.name.includes('count') ? 'INTEGER' : 'NUMERIC(12, 2)';
    case 'boolean':
      return 'BOOLEAN';
    case 'date':
      return 'TIMESTAMPTZ';
    case 'enum':
      if (field.values && field.values.length > 0) {
        const allowed = field.values.map(v => `'${v}'`).join(', ');
        return `VARCHAR(50) CHECK (${field.name} IN (${allowed}))`;
      }
      return 'VARCHAR(50)';
    default:
      return 'TEXT';
  }
}

function mapPrismaType(field: EntityField): string {
  if (typeof field.type === 'string' && field.type.startsWith('ref:')) {
    return 'String';
  }
  switch (field.type) {
    case 'string':
      return 'String';
    case 'text':
      return 'String';
    case 'number':
      return field.name.includes('days') || field.name.includes('count') ? 'Int' : 'Float';
    case 'boolean':
      return 'Boolean';
    case 'date':
      return 'DateTime';
    case 'enum':
      return 'String';
    default:
      return 'String';
  }
}

export function compileDeterministicSqlDDL(ir: IntermediateRepresentation): string {
  const lines: string[] = [
    `-- =========================================================================`,
    `-- DETERMINISTIC POSTGRESQL DDL GENERATED BY FLOE COMPILER v1.0`,
    `-- Target Domain: ${ir.domain}`,
    `-- App Name: ${ir.name}`,
    `-- Compiled at: ${new Date().toISOString()}`,
    `-- =========================================================================\n`,
    `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n`
  ];

  // 1. Compile Entities
  ir.entities.forEach((entity) => {
    const tableName = entity.name.toLowerCase() + 's';
    lines.push(`-- Table: ${entity.name} (${entity.description || 'Domain record'})`);
    lines.push(`CREATE TABLE IF NOT EXISTS ${tableName} (`);

    const fieldDefs: string[] = [];
    
    // Add primary key if not explicit in fields
    const hasId = entity.fields.some(f => f.name === 'id');
    if (!hasId) {
      fieldDefs.push(`    id UUID PRIMARY KEY DEFAULT uuid_generate_v4()`);
    }

    entity.fields.forEach(f => {
      const isPk = f.name === 'id';
      let def = `    ${f.name} ${isPk ? 'UUID PRIMARY KEY DEFAULT uuid_generate_v4()' : mapSqlType(f)}`;
      if (f.required && !isPk) {
        def += ' NOT NULL';
      }
      if (f.default !== undefined) {
        if (typeof f.default === 'string') {
          def += ` DEFAULT '${f.default}'`;
        } else {
          def += ` DEFAULT ${f.default}`;
        }
      }
      fieldDefs.push(def);
    });

    fieldDefs.push(`    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
    fieldDefs.push(`    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);

    lines.push(fieldDefs.join(',\n'));
    lines.push(`);\n`);
  });

  // 2. Foreign Key constraints and Indexes
  lines.push(`-- Referential Integrity Constraints & Indexes`);
  ir.relationships.forEach(rel => {
    const sourceTable = rel.from.toLowerCase() + 's';
    const targetTable = rel.to.toLowerCase() + 's';
    lines.push(`ALTER TABLE ${sourceTable} ADD CONSTRAINT fk_${sourceTable}_${rel.field}`);
    lines.push(`    FOREIGN KEY (${rel.field}) REFERENCES ${targetTable}(id) ON DELETE RESTRICT;`);
    lines.push(`CREATE INDEX IF NOT EXISTS idx_${sourceTable}_${rel.field} ON ${sourceTable}(${rel.field});\n`);
  });

  // 3. Standard Floe Runtime Execution Tables (Mandatory in every generated app)
  lines.push(`-- =========================================================================`);
  lines.push(`-- STANDARD FLOE PLATFORM WORKFLOW RUNTIME SCHEMAS`);
  lines.push(`-- Enables deterministic execution tracking, audit trails & AI step metrics`);
  lines.push(`-- =========================================================================\n`);

  lines.push(`CREATE TABLE IF NOT EXISTS workflow_runs (`);
  lines.push(`    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),`);
  lines.push(`    workflow_id VARCHAR(100) NOT NULL,`);
  lines.push(`    record_id UUID NOT NULL,`);
  lines.push(`    status VARCHAR(50) NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'paused_human')),`);
  lines.push(`    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),`);
  lines.push(`    completed_at TIMESTAMPTZ,`);
  lines.push(`    error TEXT`);
  lines.push(`);\n`);
  lines.push(`CREATE INDEX IF NOT EXISTS idx_workflow_runs_record ON workflow_runs(record_id);\n`);

  lines.push(`CREATE TABLE IF NOT EXISTS node_executions (`);
  lines.push(`    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),`);
  lines.push(`    workflow_run_id UUID NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,`);
  lines.push(`    node_id VARCHAR(100) NOT NULL,`);
  lines.push(`    execution_mode VARCHAR(50) NOT NULL CHECK (execution_mode IN ('deterministic', 'ai', 'agentic', 'human')),`);
  lines.push(`    status VARCHAR(50) NOT NULL CHECK (status IN ('queued', 'running', 'completed', 'failed', 'awaiting_human')),`);
  lines.push(`    input JSONB DEFAULT '{}'::jsonb,`);
  lines.push(`    output JSONB DEFAULT '{}'::jsonb,`);
  lines.push(`    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),`);
  lines.push(`    completed_at TIMESTAMPTZ,`);
  lines.push(`    error TEXT`);
  lines.push(`);\n`);
  lines.push(`CREATE INDEX IF NOT EXISTS idx_node_executions_run ON node_executions(workflow_run_id);\n`);

  // 4. Role-Based Access Control (RBAC) System Tables & Seed Data
  lines.push(`-- =========================================================================`);
  lines.push(`-- ROLE-BASED ACCESS CONTROL (RBAC) SCHEMA & SEED DATA`);
  lines.push(`-- Deterministically generated from IR roles and permissions`);
  lines.push(`-- =========================================================================\n`);

  lines.push(`CREATE TABLE IF NOT EXISTS app_roles (`);
  lines.push(`    id VARCHAR(50) PRIMARY KEY,`);
  lines.push(`    name VARCHAR(100) NOT NULL,`);
  lines.push(`    display_name VARCHAR(150) NOT NULL,`);
  lines.push(`    description TEXT,`);
  lines.push(`    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
  lines.push(`);\n`);

  lines.push(`CREATE TABLE IF NOT EXISTS app_permissions (`);
  lines.push(`    id VARCHAR(100) PRIMARY KEY,`);
  lines.push(`    category VARCHAR(50) NOT NULL,`);
  lines.push(`    description TEXT,`);
  lines.push(`    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
  lines.push(`);\n`);

  lines.push(`CREATE TABLE IF NOT EXISTS role_permissions (`);
  lines.push(`    role_id VARCHAR(50) NOT NULL REFERENCES app_roles(id) ON DELETE CASCADE,`);
  lines.push(`    permission_id VARCHAR(100) NOT NULL REFERENCES app_permissions(id) ON DELETE CASCADE,`);
  lines.push(`    PRIMARY KEY (role_id, permission_id)`);
  lines.push(`);\n`);

  lines.push(`CREATE TABLE IF NOT EXISTS app_users (`);
  lines.push(`    id VARCHAR(100) PRIMARY KEY,`);
  lines.push(`    name VARCHAR(150) NOT NULL,`);
  lines.push(`    email VARCHAR(255) NOT NULL UNIQUE,`);
  lines.push(`    password_hash VARCHAR(255) NOT NULL,`);
  lines.push(`    role_id VARCHAR(50) NOT NULL REFERENCES app_roles(id) ON DELETE RESTRICT,`);
  lines.push(`    role_title VARCHAR(150),`);
  lines.push(`    department VARCHAR(100),`);
  lines.push(`    balance NUMERIC(10,2) DEFAULT 0,`);
  lines.push(`    total_allowance NUMERIC(10,2) DEFAULT 0,`);
  lines.push(`    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
  lines.push(`);\n`);
  lines.push(`CREATE INDEX IF NOT EXISTS idx_app_users_email ON app_users(email);\n`);

  // Compile RBAC Seed Inserts from IR roles
  const roles = (ir.roles && ir.roles.length > 0) ? ir.roles : [
    { name: 'submitter', displayName: 'Submitter', description: 'Standard user who submits records', permissions: ['create:own', 'read:own'] },
    { name: 'manager', displayName: 'Manager / Approver', description: 'Approver for workflow steps', permissions: ['read:all', 'approve:step', 'update:status'] },
    { name: 'admin', displayName: 'System Admin', description: 'Full administrative access', permissions: ['read:all', 'update:all', 'admin:ddl', 'admin:audit'] }
  ];

  const uniquePermissions = new Set<string>();
  roles.forEach(r => (r.permissions || []).forEach(p => uniquePermissions.add(p)));

  lines.push(`-- Seed RBAC Roles`);
  roles.forEach(r => {
    const roleId = r.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
    const safeDesc = (r.description || `${r.displayName || r.name} role`).replace(/'/g, "''");
    const safeDisplay = (r.displayName || r.name).replace(/'/g, "''");
    lines.push(`INSERT INTO app_roles (id, name, display_name, description) VALUES ('${roleId}', '${r.name}', '${safeDisplay}', '${safeDesc}') ON CONFLICT (id) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description;`);
  });
  lines.push('');

  lines.push(`-- Seed RBAC Permissions`);
  uniquePermissions.forEach(p => {
    const safePerm = p.replace(/'/g, "''");
    const category = p.startsWith('admin:') ? 'System & Governance' : p.includes('update') || p.includes('approve') ? 'Workflow Decision' : 'Entity Data';
    lines.push(`INSERT INTO app_permissions (id, category, description) VALUES ('${safePerm}', '${category}', 'Grants authority to ${safePerm}') ON CONFLICT (id) DO NOTHING;`);
  });
  lines.push('');

  lines.push(`-- Seed Role-Permission Mappings`);
  roles.forEach(r => {
    const roleId = r.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
    (r.permissions || []).forEach(p => {
      const safePerm = p.replace(/'/g, "''");
      lines.push(`INSERT INTO role_permissions (role_id, permission_id) VALUES ('${roleId}', '${safePerm}') ON CONFLICT DO NOTHING;`);
    });
  });
  lines.push('');

  lines.push(`-- Seed Demo Personas`);
  roles.forEach((r, idx) => {
    const roleId = r.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
    const persona = r.userPersona || {
      name: `${r.displayName || r.name} User`,
      email: `${roleId}@${ir.domain}.local`,
      password: `${r.name}#2026`,
      roleTitle: r.displayName || r.name,
      department: 'Operations',
      balance: 14,
      totalAllowance: 20
    };
    const userId = `usr_${roleId}_${idx + 1}`;
    const safeName = (persona.name || 'User').replace(/'/g, "''");
    const safeEmail = (persona.email || `${roleId}@floe.internal`).replace(/'/g, "''");
    const safeTitle = (persona.roleTitle || r.displayName || r.name).replace(/'/g, "''");
    const safeDept = (persona.department || 'General').replace(/'/g, "''");
    const balance = persona.balance || 0;
    const allowance = persona.totalAllowance || 0;
    lines.push(`INSERT INTO app_users (id, name, email, password_hash, role_id, role_title, department, balance, total_allowance) VALUES ('${userId}', '${safeName}', '${safeEmail}', 'sha256_mock_hash_${roleId}', '${roleId}', '${safeTitle}', '${safeDept}', ${balance}, ${allowance}) ON CONFLICT (email) DO NOTHING;`);
  });
  lines.push('');

  return lines.join('\n');
}

export function compilePrismaSchema(ir: IntermediateRepresentation): string {
  const lines: string[] = [
    `// Prisma Schema generated deterministically by Floe Compiler`,
    `datasource db {`,
    `  provider = "postgresql"`,
    `  url      = env("DATABASE_URL")`,
    `}`,
    ``,
    `generator client {`,
    `  provider = "prisma-client-js"`,
    `}\n`
  ];

  ir.entities.forEach(entity => {
    lines.push(`model ${entity.name} {`);
    lines.push(`  id        String   @id @default(uuid())`);
    
    entity.fields.forEach(f => {
      if (f.name === 'id') return;
      const type = mapPrismaType(f);
      const optional = !f.required ? '?' : '';
      let line = `  ${f.name.padEnd(20)} ${type}${optional}`;
      if (f.default !== undefined) {
        line += ` @default(${typeof f.default === 'string' ? `"${f.default}"` : f.default})`;
      }
      lines.push(line);
    });

    lines.push(`  createdAt DateTime @default(now())`);
    lines.push(`  updatedAt DateTime @updatedAt`);
    lines.push(`}\n`);
  });

  lines.push(`model WorkflowRun {`);
  lines.push(`  id          String          @id @default(uuid())`);
  lines.push(`  workflowId  String`);
  lines.push(`  recordId    String`);
  lines.push(`  status      String`);
  lines.push(`  startedAt   DateTime        @default(now())`);
  lines.push(`  completedAt DateTime?`);
  lines.push(`  error       String?`);
  lines.push(`  nodes       NodeExecution[]`);
  lines.push(`}\n`);

  lines.push(`model NodeExecution {`);
  lines.push(`  id            String      @id @default(uuid())`);
  lines.push(`  workflowRunId String`);
  lines.push(`  workflowRun   WorkflowRun @relation(fields: [workflowRunId], references: [id])`);
  lines.push(`  nodeId        String`);
  lines.push(`  executionMode String`);
  lines.push(`  status        String`);
  lines.push(`  input         Json?`);
  lines.push(`  output        Json?`);
  lines.push(`  startedAt     DateTime    @default(now())`);
  lines.push(`  completedAt   DateTime?`);
  lines.push(`  error         String?`);
  lines.push(`}\n`);

  lines.push(`model AppRole {`);
  lines.push(`  id          String           @id`);
  lines.push(`  name        String`);
  lines.push(`  displayName String`);
  lines.push(`  description String?`);
  lines.push(`  users       AppUser[]`);
  lines.push(`  permissions RolePermission[]`);
  lines.push(`  createdAt   DateTime         @default(now())`);
  lines.push(`}\n`);

  lines.push(`model AppPermission {`);
  lines.push(`  id          String           @id`);
  lines.push(`  category    String`);
  lines.push(`  description String?`);
  lines.push(`  roles       RolePermission[]`);
  lines.push(`  createdAt   DateTime         @default(now())`);
  lines.push(`}\n`);

  lines.push(`model RolePermission {`);
  lines.push(`  roleId       String`);
  lines.push(`  permissionId String`);
  lines.push(`  role         AppRole       @relation(fields: [roleId], references: [id])`);
  lines.push(`  permission   AppPermission @relation(fields: [permissionId], references: [id])`);
  lines.push(`  @@id([roleId, permissionId])`);
  lines.push(`}\n`);

  lines.push(`model AppUser {`);
  lines.push(`  id             String   @id`);
  lines.push(`  name           String`);
  lines.push(`  email          String   @unique`);
  lines.push(`  passwordHash   String`);
  lines.push(`  roleId         String`);
  lines.push(`  role           AppRole  @relation(fields: [roleId], references: [id])`);
  lines.push(`  roleTitle      String?`);
  lines.push(`  department     String?`);
  lines.push(`  balance        Float    @default(0)`);
  lines.push(`  totalAllowance Float    @default(0)`);
  lines.push(`  createdAt      DateTime @default(now())`);
  lines.push(`}\n`);

  return lines.join('\n');
}

export function computeIrHash(ir: IntermediateRepresentation): string {
  const str = JSON.stringify({
    domain: ir.domain,
    entities: ir.entities,
    relationships: ir.relationships,
    roles: ir.roles,
    workflows: ir.workflows
  });
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return 'ir_hash_' + Math.abs(hash).toString(16);
}
